language: rust
rust: stable

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - cargo doc --no-deps --lib
  - cp -r target/doc/* book/book

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: rust-spandex/spandex
  target_branch: gh-pages
  local_dir: target/doc/
  on:
    branch: master

